version: "3"

services:
  db:
    image: postgres:10
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
  graphql:
    build:
      context: ./graphql
    ports:
      - "5000:5000"
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app