version: "3"

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  graphql:
    build:
      context: ./graphql
    ports:
      - "5000:5000"
    volumes:
      - ./graphql:/app
      - /app/node_modules
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
